version: '3.1'

services:
  jrtb-db:
    image: mysql
    restart: always
    container_name: dev-jrtb-db
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: "library"
      MYSQL_ROOT_PASSWORD: password